import { createFileRoute } from "@tanstack/react-router";
import { PageHeader } from "@/components/portal-shell";
import {
  AlertTriangle,
  CheckCircle2,
  Clock,
  Heart,
  MapPin,
  Shield,
  Sparkles,
  Timer,
  Users,
  Printer,
  FileSearch,
} from "lucide-react";

export const Route = createFileRoute("/admin/case")({
  component: CaseReport,
});

const timeline: { at: string; label: string; detail: string; tone: "blue" | "amber" | "green" }[] = [
  { at: "18:42:00", label: "Incident reported", detail: "Fan alert triggered from Section 118, row 22.", tone: "blue" },
  { at: "18:42:04", label: "AI triage complete", detail: "Classified as Medical Emergency — High Priority.", tone: "amber" },
  { at: "18:42:11", label: "Medical Team 3 dispatched", detail: "Nearest team routed via service corridor B.", tone: "amber" },
  { at: "18:44:14", label: "On scene", detail: "Response time: 2 min 14 sec. Fan assessed by paramedic.", tone: "amber" },
  { at: "18:49:38", label: "Fan stabilized", detail: "Vitals stable. Prepared for transport.", tone: "green" },
  { at: "18:54:02", label: "Transported to medical center", detail: "Handover completed. Section 118 cleared.", tone: "green" },
];

function CaseReport() {
  return (
    <div>
      <PageHeader
        title="Case Report"
        description="Post-incident review generated by Stadium Brain AI."
      />

      <div className="mb-4 flex flex-wrap items-center gap-2">
        <span className="inline-flex items-center gap-1.5 rounded-full bg-accent/15 px-3 py-1 text-[11px] font-semibold uppercase tracking-widest text-accent ring-1 ring-accent/40">
          <CheckCircle2 className="h-3 w-3" /> Resolved
        </span>
        <span className="inline-flex items-center gap-1.5 rounded-full bg-destructive/15 px-3 py-1 text-[11px] font-semibold uppercase tracking-widest text-destructive ring-1 ring-destructive/40">
          High Priority
        </span>
        <span className="font-mono text-[11px] text-muted-foreground">INC-2031</span>
        <button
          onClick={() => window.print()}
          className="ml-auto inline-flex items-center gap-1.5 rounded-lg border border-border/60 bg-card px-3 py-1.5 text-xs font-semibold hover:bg-secondary"
        >
          <Printer className="h-3.5 w-3.5" /> Print
        </button>
      </div>

      <div className="rounded-2xl border border-border/60 bg-gradient-to-br from-card to-secondary/40 p-5 shadow-card">
        <div className="flex items-start gap-4">
          <div className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-destructive/15 text-destructive ring-1 ring-destructive/40">
            <Heart className="h-5 w-5" />
          </div>
          <div className="min-w-0 flex-1">
            <div className="text-[10px] uppercase tracking-widest text-muted-foreground">Incident type</div>
            <div className="text-xl font-bold">Medical Emergency</div>
            <div className="mt-1 flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-muted-foreground">
              <span className="inline-flex items-center gap-1"><MapPin className="h-3 w-3" /> Section 118</span>
              <span className="inline-flex items-center gap-1"><Clock className="h-3 w-3" /> Reported 18:42</span>
              <span className="inline-flex items-center gap-1"><Users className="h-3 w-3" /> Medical Team 3</span>
            </div>
          </div>
        </div>
      </div>

      <div className="mt-4 grid gap-4 md:grid-cols-3">
        <Metric icon={AlertTriangle} tone="text-destructive bg-destructive/15 ring-destructive/40" label="AI Assessment" value="High Priority" hint="Triaged in 4 seconds" />
        <Metric icon={Timer} tone="text-chart-3 bg-chart-3/15 ring-chart-3/40" label="Response Time" value="2m 14s" hint="Target: under 3m" />
        <Metric icon={CheckCircle2} tone="text-accent bg-accent/15 ring-accent/40" label="Outcome" value="Stabilized" hint="Transported to medical center" />
      </div>

      <div className="mt-4 grid gap-4 lg:grid-cols-[1fr_320px]">
        <div className="rounded-2xl border border-border/60 bg-card p-5 shadow-card">
          <div className="mb-3 flex items-center gap-2">
            <div className="grid h-8 w-8 place-items-center rounded-lg bg-primary/15 text-primary ring-1 ring-primary/30">
              <Clock className="h-4 w-4" />
            </div>
            <div>
              <div className="text-sm font-semibold">Response timeline</div>
              <div className="text-[11px] text-muted-foreground">End-to-end reconstruction from AI + CCTV logs</div>
            </div>
          </div>
          <ol className="space-y-4 border-l border-border/60 pl-5">
            {timeline.map((t, i) => (
              <li key={i} className="relative">
                <span className={`absolute -left-[26px] top-1 grid h-4 w-4 place-items-center rounded-full ring-2 ring-background ${
                  t.tone === "green" ? "bg-accent shadow-[0_0_12px_hsl(var(--accent))]" :
                  t.tone === "amber" ? "bg-chart-3 shadow-[0_0_12px_hsl(var(--chart-3))]" :
                  "bg-primary shadow-glow"
                }`} />
                <div className="flex flex-wrap items-baseline gap-2">
                  <span className="text-sm font-semibold">{t.label}</span>
                  <span className="font-mono text-[11px] tabular-nums text-muted-foreground">{t.at}</span>
                </div>
                <div className="mt-0.5 text-xs text-muted-foreground">{t.detail}</div>
              </li>
            ))}
          </ol>
        </div>

        <div className="space-y-4">
          <div className="rounded-2xl border border-primary/30 bg-gradient-to-br from-primary/10 to-transparent p-5">
            <div className="mb-2 flex items-center gap-2 text-primary">
              <Sparkles className="h-4 w-4" />
              <span className="text-[10px] font-bold uppercase tracking-widest">AI recommendation</span>
            </div>
            <p className="text-sm leading-relaxed">
              Increase medical staff coverage near <span className="font-semibold text-foreground">Section 118</span> during halftime due to historically high congestion.
            </p>
            <div className="mt-3 grid gap-2 text-[11px]">
              <Row label="Expected impact" value="−32% response time" />
              <Row label="Confidence" value="92%" />
              <Row label="Data basis" value="17 similar incidents · 6 months" />
            </div>
          </div>

          <div className="rounded-2xl border border-border/60 bg-card p-5">
            <div className="mb-3 flex items-center gap-2">
              <Shield className="h-4 w-4 text-accent" />
              <span className="text-sm font-semibold">Action taken</span>
            </div>
            <p className="text-xs leading-relaxed text-muted-foreground">
              Medical Team 3 dispatched via service corridor B. Fan stabilized on-site and transported to the stadium medical center for observation.
            </p>
          </div>

          <div className="rounded-2xl border border-border/60 bg-card p-5">
            <div className="mb-3 flex items-center gap-2">
              <FileSearch className="h-4 w-4 text-primary" />
              <span className="text-sm font-semibold">Case metadata</span>
            </div>
            <div className="space-y-1.5 text-[11px]">
              <Row label="Incident ID" value="INC-2031" />
              <Row label="Reported" value="18:42:00" />
              <Row label="Closed" value="18:54:02" />
              <Row label="Total duration" value="12m 02s" />
              <Row label="Reviewer" value="Ops Supervisor" />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function Metric({
  icon: Icon,
  tone,
  label,
  value,
  hint,
}: {
  icon: typeof AlertTriangle;
  tone: string;
  label: string;
  value: string;
  hint: string;
}) {
  return (
    <div className="rounded-2xl border border-border/60 bg-card p-4 shadow-card">
      <div className="flex items-center gap-3">
        <div className={`grid h-10 w-10 place-items-center rounded-lg ring-1 ${tone}`}>
          <Icon className="h-4 w-4" />
        </div>
        <div className="min-w-0">
          <div className="text-[10px] uppercase tracking-widest text-muted-foreground">{label}</div>
          <div className="text-lg font-bold leading-tight">{value}</div>
          <div className="text-[11px] text-muted-foreground">{hint}</div>
        </div>
      </div>
    </div>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between gap-3">
      <span className="text-muted-foreground">{label}</span>
      <span className="font-medium text-foreground">{value}</span>
    </div>
  );
}