/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FanRouteImport } from './routes/fan'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FanIndexRouteImport } from './routes/fan.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as FanMatchRouteImport } from './routes/fan.match'
import { Route as FanMapRouteImport } from './routes/fan.map'
import { Route as FanFoodRouteImport } from './routes/fan.food'
import { Route as FanEmergencyRouteImport } from './routes/fan.emergency'
import { Route as FanCrowdRouteImport } from './routes/fan.crowd'
import { Route as FanAccessibilityRouteImport } from './routes/fan.accessibility'
import { Route as AdminQueuesRouteImport } from './routes/admin.queues'
import { Route as AdminMissionRouteImport } from './routes/admin.mission'
import { Route as AdminIncidentsRouteImport } from './routes/admin.incidents'
import { Route as AdminHeatmapRouteImport } from './routes/admin.heatmap'
import { Route as AdminEmergencyRouteImport } from './routes/admin.emergency'
import { Route as AdminCrowdRouteImport } from './routes/admin.crowd'
import { Route as AdminAiRouteImport } from './routes/admin.ai'

const FanRoute = FanRouteImport.update({
  id: '/fan',
  path: '/fan',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FanIndexRoute = FanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FanRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const FanMatchRoute = FanMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => FanRoute,
} as any)
const FanMapRoute = FanMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => FanRoute,
} as any)
const FanFoodRoute = FanFoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => FanRoute,
} as any)
const FanEmergencyRoute = FanEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => FanRoute,
} as any)
const FanCrowdRoute = FanCrowdRouteImport.update({
  id: '/crowd',
  path: '/crowd',
  getParentRoute: () => FanRoute,
} as any)
const FanAccessibilityRoute = FanAccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => FanRoute,
} as any)
const AdminQueuesRoute = AdminQueuesRouteImport.update({
  id: '/queues',
  path: '/queues',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMissionRoute = AdminMissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIncidentsRoute = AdminIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHeatmapRoute = AdminHeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmergencyRoute = AdminEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCrowdRoute = AdminCrowdRouteImport.update({
  id: '/crowd',
  path: '/crowd',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/fan': typeof FanRouteWithChildren
  '/admin/ai': typeof AdminAiRoute
  '/admin/crowd': typeof AdminCrowdRoute
  '/admin/emergency': typeof AdminEmergencyRoute
  '/admin/heatmap': typeof AdminHeatmapRoute
  '/admin/incidents': typeof AdminIncidentsRoute
  '/admin/mission': typeof AdminMissionRoute
  '/admin/queues': typeof AdminQueuesRoute
  '/fan/accessibility': typeof FanAccessibilityRoute
  '/fan/crowd': typeof FanCrowdRoute
  '/fan/emergency': typeof FanEmergencyRoute
  '/fan/food': typeof FanFoodRoute
  '/fan/map': typeof FanMapRoute
  '/fan/match': typeof FanMatchRoute
  '/admin/': typeof AdminIndexRoute
  '/fan/': typeof FanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/crowd': typeof AdminCrowdRoute
  '/admin/emergency': typeof AdminEmergencyRoute
  '/admin/heatmap': typeof AdminHeatmapRoute
  '/admin/incidents': typeof AdminIncidentsRoute
  '/admin/mission': typeof AdminMissionRoute
  '/admin/queues': typeof AdminQueuesRoute
  '/fan/accessibility': typeof FanAccessibilityRoute
  '/fan/crowd': typeof FanCrowdRoute
  '/fan/emergency': typeof FanEmergencyRoute
  '/fan/food': typeof FanFoodRoute
  '/fan/map': typeof FanMapRoute
  '/fan/match': typeof FanMatchRoute
  '/admin': typeof AdminIndexRoute
  '/fan': typeof FanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/fan': typeof FanRouteWithChildren
  '/admin/ai': typeof AdminAiRoute
  '/admin/crowd': typeof AdminCrowdRoute
  '/admin/emergency': typeof AdminEmergencyRoute
  '/admin/heatmap': typeof AdminHeatmapRoute
  '/admin/incidents': typeof AdminIncidentsRoute
  '/admin/mission': typeof AdminMissionRoute
  '/admin/queues': typeof AdminQueuesRoute
  '/fan/accessibility': typeof FanAccessibilityRoute
  '/fan/crowd': typeof FanCrowdRoute
  '/fan/emergency': typeof FanEmergencyRoute
  '/fan/food': typeof FanFoodRoute
  '/fan/map': typeof FanMapRoute
  '/fan/match': typeof FanMatchRoute
  '/admin/': typeof AdminIndexRoute
  '/fan/': typeof FanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/fan'
    | '/admin/ai'
    | '/admin/crowd'
    | '/admin/emergency'
    | '/admin/heatmap'
    | '/admin/incidents'
    | '/admin/mission'
    | '/admin/queues'
    | '/fan/accessibility'
    | '/fan/crowd'
    | '/fan/emergency'
    | '/fan/food'
    | '/fan/map'
    | '/fan/match'
    | '/admin/'
    | '/fan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/ai'
    | '/admin/crowd'
    | '/admin/emergency'
    | '/admin/heatmap'
    | '/admin/incidents'
    | '/admin/mission'
    | '/admin/queues'
    | '/fan/accessibility'
    | '/fan/crowd'
    | '/fan/emergency'
    | '/fan/food'
    | '/fan/map'
    | '/fan/match'
    | '/admin'
    | '/fan'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/fan'
    | '/admin/ai'
    | '/admin/crowd'
    | '/admin/emergency'
    | '/admin/heatmap'
    | '/admin/incidents'
    | '/admin/mission'
    | '/admin/queues'
    | '/fan/accessibility'
    | '/fan/crowd'
    | '/fan/emergency'
    | '/fan/food'
    | '/fan/map'
    | '/fan/match'
    | '/admin/'
    | '/fan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  FanRoute: typeof FanRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/fan': {
      id: '/fan'
      path: '/fan'
      fullPath: '/fan'
      preLoaderRoute: typeof FanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fan/': {
      id: '/fan/'
      path: '/'
      fullPath: '/fan/'
      preLoaderRoute: typeof FanIndexRouteImport
      parentRoute: typeof FanRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/fan/match': {
      id: '/fan/match'
      path: '/match'
      fullPath: '/fan/match'
      preLoaderRoute: typeof FanMatchRouteImport
      parentRoute: typeof FanRoute
    }
    '/fan/map': {
      id: '/fan/map'
      path: '/map'
      fullPath: '/fan/map'
      preLoaderRoute: typeof FanMapRouteImport
      parentRoute: typeof FanRoute
    }
    '/fan/food': {
      id: '/fan/food'
      path: '/food'
      fullPath: '/fan/food'
      preLoaderRoute: typeof FanFoodRouteImport
      parentRoute: typeof FanRoute
    }
    '/fan/emergency': {
      id: '/fan/emergency'
      path: '/emergency'
      fullPath: '/fan/emergency'
      preLoaderRoute: typeof FanEmergencyRouteImport
      parentRoute: typeof FanRoute
    }
    '/fan/crowd': {
      id: '/fan/crowd'
      path: '/crowd'
      fullPath: '/fan/crowd'
      preLoaderRoute: typeof FanCrowdRouteImport
      parentRoute: typeof FanRoute
    }
    '/fan/accessibility': {
      id: '/fan/accessibility'
      path: '/accessibility'
      fullPath: '/fan/accessibility'
      preLoaderRoute: typeof FanAccessibilityRouteImport
      parentRoute: typeof FanRoute
    }
    '/admin/queues': {
      id: '/admin/queues'
      path: '/queues'
      fullPath: '/admin/queues'
      preLoaderRoute: typeof AdminQueuesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mission': {
      id: '/admin/mission'
      path: '/mission'
      fullPath: '/admin/mission'
      preLoaderRoute: typeof AdminMissionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/incidents': {
      id: '/admin/incidents'
      path: '/incidents'
      fullPath: '/admin/incidents'
      preLoaderRoute: typeof AdminIncidentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/heatmap': {
      id: '/admin/heatmap'
      path: '/heatmap'
      fullPath: '/admin/heatmap'
      preLoaderRoute: typeof AdminHeatmapRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emergency': {
      id: '/admin/emergency'
      path: '/emergency'
      fullPath: '/admin/emergency'
      preLoaderRoute: typeof AdminEmergencyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/crowd': {
      id: '/admin/crowd'
      path: '/crowd'
      fullPath: '/admin/crowd'
      preLoaderRoute: typeof AdminCrowdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAiRoute: typeof AdminAiRoute
  AdminCrowdRoute: typeof AdminCrowdRoute
  AdminEmergencyRoute: typeof AdminEmergencyRoute
  AdminHeatmapRoute: typeof AdminHeatmapRoute
  AdminIncidentsRoute: typeof AdminIncidentsRoute
  AdminMissionRoute: typeof AdminMissionRoute
  AdminQueuesRoute: typeof AdminQueuesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiRoute: AdminAiRoute,
  AdminCrowdRoute: AdminCrowdRoute,
  AdminEmergencyRoute: AdminEmergencyRoute,
  AdminHeatmapRoute: AdminHeatmapRoute,
  AdminIncidentsRoute: AdminIncidentsRoute,
  AdminMissionRoute: AdminMissionRoute,
  AdminQueuesRoute: AdminQueuesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface FanRouteChildren {
  FanAccessibilityRoute: typeof FanAccessibilityRoute
  FanCrowdRoute: typeof FanCrowdRoute
  FanEmergencyRoute: typeof FanEmergencyRoute
  FanFoodRoute: typeof FanFoodRoute
  FanMapRoute: typeof FanMapRoute
  FanMatchRoute: typeof FanMatchRoute
  FanIndexRoute: typeof FanIndexRoute
}

const FanRouteChildren: FanRouteChildren = {
  FanAccessibilityRoute: FanAccessibilityRoute,
  FanCrowdRoute: FanCrowdRoute,
  FanEmergencyRoute: FanEmergencyRoute,
  FanFoodRoute: FanFoodRoute,
  FanMapRoute: FanMapRoute,
  FanMatchRoute: FanMatchRoute,
  FanIndexRoute: FanIndexRoute,
}

const FanRouteWithChildren = FanRoute._addFileChildren(FanRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  FanRoute: FanRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
